### ISSUE TITLE
Broken pipe failure during test runs

### ISSUE THREAD

**Issue by brynary** [ngauthier/hydra#18]
Tests are failing for me (on a clean checkout) like this:

[ree-1.8.7] [06:46:10] $ rake
(in /Users/bhelmkamp/p/active/hydra)
/Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/jeweler-1.4.0/lib/jeweler/commands/check_dependencies.rb:13:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
All dependencies seem to be installed.
/Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/bin/ruby -I"lib:lib:test" "/Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/fixtures/sync_test.rb" "test/master_test.rb" "test/message_test.rb" "test/pipe_test.rb" "test/runner_test.rb" "test/ssh_test.rb" "test/sync_test.rb" "test/worker_test.rb" 
Loaded suite /Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
....../test/../lib/hydra/ssh.rb:30:in `write': Broken pipe (Errno::EPIPE)
    from ./test/../lib/hydra/ssh.rb:30:in`initialize'
    from ./test/../lib/hydra/master.rb:174:in `new'
    from ./test/../lib/hydra/master.rb:174:in`boot_ssh_worker'
    from ./test/../lib/hydra/master.rb:196:in `process_messages'
    from ./test/../lib/hydra/master.rb:193:in`initialize'
    from ./test/../lib/hydra/master.rb:193:in `new'
    from ./test/../lib/hydra/master.rb:193:in`process_messages'
    from ./test/../lib/hydra/master.rb:192:in `each'
    from ./test/../lib/hydra/master.rb:192:in`process_messages'
    from ./test/../lib/hydra/master.rb:86:in `initialize'
    from ./test/master_test.rb:84:in`new'
    from ./test/master_test.rb:84:in `__bind_1282474024_539126'
    from /Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/shoulda-2.11.1/lib/shoulda/context.rb:382:in`call'
    from /Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/shoulda-2.11.1/lib/shoulda/context.rb:382:in `test: with a file to test and a destination to verify should run a test via ssh. '
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testcase.rb:78:in`**send**'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testcase.rb:78:in `run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:34:in`run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:33:in `each'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:33:in`run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:34:in `run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:33:in`each'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/testsuite.rb:33:in `run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/ui/testrunnermediator.rb:46:in`run_suite'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/ui/console/testrunner.rb:67:in `start_mediator'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/ui/console/testrunner.rb:41:in`start'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/ui/testrunnerutilities.rb:29:in `run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/autorunner.rb:216:in`run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit/autorunner.rb:12:in `run'
    from /Users/bhelmkamp/.rvm/rubies/ree-1.8.7-2010.01/lib/ruby/1.8/test/unit.rb:279
    from /Users/bhelmkamp/.rvm/gems/ree-1.8.7-2010.01/gems/rake-0.8.7/lib/rake/rake_test_loader.rb:5
rake aborted!
Command failed with status (1): [/Users/bhelmkamp/.rvm/rubies/ree-1.8.7-201...]

(See full trace by running task with --trace)

**Comment by ngauthier** [comment]
SSH and pipe requirements:
http://wiki.github.com/ngauthier/hydra/development-environment
