### ISSUE TITLE
undefined method `options=' when running hydra for cucumber

### ISSUE THREAD

**Issue by raldred** [ngauthier/hydra#23]
rake hydra:cucumber fails.
Versions:
Hydra: 0.22.2
Cucumber 0.9.0

``run_cucumber_file': undefined method options=' for #<Cucumber::StepMother:0x10362d4d8> (NoMethodError)`

```
/Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/runner.rb:148:in `run_cucumber_file': undefined method options=' for #<Cucumber::StepMother:0x10362d4d8> (NoMethodError)
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/runner.rb:41:in `run_file'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/message/worker_messages.rb:25:in `handle'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/runner.rb:71:in `process_messages'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/runner.rb:26:in `initialize'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:86:in `new'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:86:in `boot_runners'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/safe_fork.rb:15:in `fork'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/safe_fork.rb:7:in `fork'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:84:in `boot_runners'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:82:in `times'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:82:in `boot_runners'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/worker.rb:24:in `initialize'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:163:in `new'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:163:in `boot_local_worker'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/safe_fork.rb:15:in `fork'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/safe_fork.rb:7:in `fork'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:161:in `boot_local_worker'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:148:in `boot_workers'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:143:in `each'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:143:in `boot_workers'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/master.rb:87:in `initialize'
from /Users/robaldred/.rvm/gems/ruby-1.8.7-p249@kitten/gems/hydra-0.22.2/lib/hydra/tasks.rb:112:in `new'
```

**Comment by gshankar** [comment]
I'm getting this too. I was actually getting issues with routes (very basic routes like users_path which work under the normal test environment) in the actual app I wanted to test so I created a fresh Rails 3 application to see if that solved my issue but now I'm getting this error instead...

**Comment by raldred** [comment]
hey, the issue is actually that hydra doesn't support cucumber 0.9 yet.
I have done some work to make it so, just discussing at the moment with Nick about merging it in.

**Comment by gshankar** [comment]
Cool, thanks for the update. Looking forward to seeing the merge!
