### ISSUE TITLE
no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by Dakuan** [ngauthier/hydra#57]
Code is railing on a file open :( I've placed a puts statement just before the offending line to find out what file is not happy about and its '/tmp/hydra_heuristics.yml' which sure enough doesn't exist. Is there some kind of generator that needs to be run or something like that?

Full stack trace:

```
** Invoke hydra:cucumber (first_time)
** Execute hydra:cucumber
********************
""
dom-> /tmp/hydra_heuristics.yml
rake aborted!
no implicit conversion from nil to integer
/Users/Dom/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:298:in `initialize'
/Users/Dom/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:298:in `open'
/Users/Dom/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:298:in `load_file'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/hydra-0.24.0/lib/hydra/master.rb:232:in `sort_files_from_report'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/hydra-0.24.0/lib/hydra/master.rb:78:in `initialize'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/hydra-0.24.0/lib/hydra/tasks.rb:137:in `new'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/hydra-0.24.0/lib/hydra/tasks.rb:137:in `block in define'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/Dom/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/bin/rake:19:in `load'
/Users/Dom/.rvm/gems/ruby-1.9.3-p194/bin/rake:19:in `<main>'
Tasks: TOP => hydra:cucumber

```

**Comment by Dakuan** [comment]
Weirdly, this issue only occurs on the 2nd occasion that the tests are run. If I reboot the machine, they will run - once.

**Comment by ngauthier** [comment]
That is odd.

Although Hydra has not seen much work in a few years, I am not sure how compatible it is with ruby 1.9.3. This seems to be a yaml parsing issue, but hydra is also the one writing the yaml file, so I'm not sure why it would create a file it can't read.
